### ISSUE TITLE
Is there a way to recursively iterate the key?

### ISSUE THREAD

**Issue by MacHu-GWU** [ICRAR/ijson#103]
**Is your feature request related to a problem? Please describe.**

Sometime the big json array node is deeply nested inside. I am wondering if you have a method that is similar to ``kvitems``, however, the value it returns is a lazy-load iterable object instead of a concrete list. Then we can surgically delete that big json array node without loading everything into memory.

**Describe the solution you'd like**

Consider the following example.

```python
{
    "id": 1,
    "data": {
        "name": "alice",
        "records": [
            {"key": 1},
            {"key": 2},
            {"key": 3}
        ]
    }
}

f = open("data.json", "r")
new_data = {}
for k, v in ijson.kvitems(f, "", lazyload=True):
    if k == "data":
        data_dct = {}
        for k1, v1 in ijson.kvitems(v, lazyload=True):
            if k == "records":
                pass
            else:
                data_dct[k1] = v1
    else:
        new_data[k] = v
new_data["data"] = data_dct
```

**Describe alternatives you've considered**

any of existing solution has to load everything into memory.

**Comment by rtobar** [comment]
@MacHu-GWU thanks for expressing your interest. To answer your direction question "Is there a way to recursively iterate the key?" the answer is: no, there's no way to do that. Since `kvitems` yields `(key, value)` pairs from an object, it needs to know when the value for a given key ends (so it know what the next key is), which in turn means the value's contents need to be scanned fully.

However, while `kvitems` indeed cannot do what you want it to do, it doesn't mean that `ijson` doesn't offer solutions for your problem. In particular, you probably want to use `ijson.parse` to iterate over the individual outputs of the parsing process, and their paths, to build up your object so it doesn't include those big `"records"` lists.

You can see some documentation about `ijson.parse` in the ijson README. If you want to understand what `ijson.parse` outputs you can use the `ijson.dump` utility (again, see the README). In addition, you might want to use the `ObjectBuilder` object to build up your final object (you can get inspiration on how to do it by looking at https://github.com/ICRAR/ijson/blob/master/ijson/common.py#L140 and https://github.com/ICRAR/ijson/blob/master/ijson/common.py#L165, which is how `items` and `kvitems` use the output of `parse` and an `ObjectBuilder` to construct their outputs). `ObjectBuilder` is not publicly documented, but at the same time I have no plans on removing it any time soon, so I'd say it's fairly safe to use (or just copy it if you want).

**Comment by MacHu-GWU** [comment]
Thank you for your awesome answer. I think the key is to make the value of (key, value) pair from kvitems method to be a Lazy load object.

Thank you again for this awesome project. We are using this library to split super big JSON into many smaller files without using too much memory.

**Comment by rtobar** [comment]
@MacHu-GWU on the understanding that it's not possible to satisfy your original request, I'll be closing this issue. Hopefully the suggested solution works for you.

**Comment by MacHu-GWU** [comment]
sure, we can close this issue.
