### ISSUE TITLE
Breaking change in version 2.5

### ISSUE THREAD

**Issue by roll** [ICRAR/ijson#13]
# Overview

Hi, it seems there is a breaking change in version 2.5 which should not be breaking according to SemVer:

```
items = ijson.items(self.__chars, path)
E       TypeError: expected bytes, str found
```

It breaks all out stack https://github.com/frictionlessdata for all new installations (because of the `tabulator-py` dependency)

Is it possible to handle this change differently? For example, deprecating the previous behavior while supporting it until the next major version or something like this.

**Comment by caduvieira** [comment]
Maybe related to #12 

Look https://github.com/ICRAR/ijson/issues/12#issuecomment-533678326

**Comment by roll** [comment]
Ok. Thanks. I've rebased `tabulator` on `ijson@2.5` - https://github.com/frictionlessdata/tabulator-py/commit/16af3dee9ebf22cd2cff38ea319833aff3941d96 - and it works. My main point was that the change like this is not what you expect on the minor release) I would consider preserving compatibility at least until `ijson@3`. But thanks anyway.

**Comment by rtobar** [comment]
I hadn't realised the python backend was different in this aspect from the other ones -- all other backends (which I tend to focus more on) work with bytes and have always failed when a string reader is passed, while the python backend is the only one that can take either. This definitely wasn't an intentional change, but an effect on changing the default backend from python to the fastest available.

Regarding breaking backwards compatibility and how to handle it now that this new version is out there, I'm a bit torn. On the one hand I understand that the default backend that gets selected behaves now differently, but on the other the change on default backend selection is documented, and explicitly selecting a backend is still possible (and their behaviours haven't changed), so users relying on the behavior of the python backend can easily continue using it. I think at the end of the day I'll probably end up releasing an ijson 2.5.1 with the warning you suggest to avoid further confusion.

**Comment by bz2** [comment]
Caught this breakage in our CI when docker images updated today. Will update our `tabulator-py` version pin to fix.

**Comment by rtobar** [comment]
A new 2.5.1 version has been uploaded to PyPI to add the automatic reader conversion to the other backends, restoring backwards compatibility for users of the default ijson backend. A warning is shown when users access this functionality to indicate they should move to byte-based readers.
