### ISSUE TITLE
How to escape special characters in prefix?

### ISSUE THREAD

**Issue by macamhi** [ICRAR/ijson#49]
I have dots, spaces and parentheses in the keys of my JSON : how do I reference them in the prefix? Escaping them with a backslash doesn't seem to work.

**Comment by rtobar** [comment]
@macamhi did you try *not* escaping them? There shouldn't be a need to.

**Comment by macamhi** [comment]
I believe at least dots might need to be escaped, as they are used to separate different levels in the path? Any way, doesn't work for me, but I'm not using ijson directly, but through integration in another application, it's just that it seemed to me that there might be an escape rule that I wasn't aware about.

**Comment by rtobar** [comment]
@macamhi dots don't need to be escaped, although there was a bug in the 3.1 that was fixed with 3.1.4, see #41 for details. Dots have [a different restriction](https://github.com/ICRAR/ijson/issues/41#issuecomment-785751177), but referencing them in the prefix is not one of them.

If after that you still have issues, please provide a reproducible example that explains your actual problem and that I can have a look at. That would further clarify whether there is actually a bug in the library, or if there is an problem somewhere else. If there is no problem then let's close this ticket.

**Comment by rtobar** [comment]
It's been a while and no further information has been presented, so I'm closing this issue.
