### ISSUE TITLE
Release wheels for 3.10

### ISSUE THREAD

**Issue by gaborbernat** [ICRAR/ijson#63]
Thanks 👍

**Comment by rtobar** [comment]
Will do when I get some time, thanks for pointing out 👍

**Comment by gaborbernat** [comment]
You might want to have a look at https://cibuildwheel.readthedocs.io/en/stable/ to automate this for the future :+1:

**Comment by rtobar** [comment]
Yes, that's what we use already

**Comment by rtobar** [comment]
I manually (with pypa's manylinux2010 docker image) generated a 3.1.4 manylinux2010 binary wheel for Linux systems and uploaded it [to PyPI](https://files.pythonhosted.org/packages/b2/1f/7014377e7e1b1af3c7dd3e4ccb2a91a90a647e93f0deccb51b5629b608d9/ijson-3.1.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl). Once a new ijson version is cut, the normal cibuildwheel process will generate the wheels for the relevant python versions.

I didn't go through an automatic CI-driven build because I don't want to tag just yet a new ijson version just to generate and upload one missing wheel. I only generated a linux, x86-64 3.10 wheel because the [download statistics](https://pypistats.org/packages/ijson) show that 3.10 represents less than 0.5% of all total downloads, while Linux represents >98% of all downloads, so most people will be well served with this new wheel I think.

With that I'm closing this ticket now.
