### ISSUE TITLE
Can read a stream of JSON from a file descriptor

### ISSUE THREAD

**Issue by stuz5000** [ICRAR/ijson#72]
Reading:
  https://github.com/ICRAR/ijson#asyncio-support
  
its not clear whether this library can be used to read a stream of JSON object from, say, a file descriptor.
Is it possible? That is if we open a file, or pipe, can we read, say:

```{ ...json object... }{...next json object...}```

... the parser to provide the object framing.

Or just a good, can we supply an infinite comma delimited list as a stream asynchronously, and without having to wait until the end of the stream :
  ```[  <json object1>  ,  <json object2>   ,       ...  ```
  ?

**Comment by rtobar** [comment]
@stuz5000 there seem to be several questions here, so I'm answering them individually. I can't clearly see the connection between all of them though, so it would be much better if you posted a code sample to understand your end goal, and what you are trying out to achieve it, which would probably serve as a better description.

> whether this library can be used to read a stream of JSON object from, say, a file descriptor

If you have a file descriptor you can wrap it with `os.fdopen` to get a file object that you can pass to ijson:

```python
file_object = os.fdopen(fd, 'rb')
for o in ijson.items(file_object, prefix):
    ...
```

> can we supply an infinite comma delimited list as a stream asynchronously

You can if you pass an asynchronous file-like object (something with an `async def read()`)

> and without having to wait until the end of the stream

Since you are doing the iteration you can always decide to `break` from it, there's no need to always go through the whole iteration if not necessary. Unless I'm not understanding your question?
