### ISSUE TITLE
How to define a prefix where an object contains dot characters

### ISSUE THREAD

**Issue by mrsant** [ICRAR/ijson#76]
```
{ "domains": {
  "this.co.uk": {
    "serial":123455,
    "owner": "fred"
  },
  "that.com": {
    "serial":234567,
    "owner": "wilma"
  },
  {...}
}
```
Assume this file is too large and needs ijson to parse for the contents of ['domains']['this.co.uk']

how is the prefix constructed?

`ijson.items(fp, 'domains.this.co.uk')` clearly isn't going to work.

I can't find anything explaining the escaping required in the docs. Thanks!

**Comment by rtobar** [comment]
@mrsant it seems you didn't try the prefix you mentioned, because that works:

```
$> echo '{"domains": {"this.co.uk": ["a","b","c"]} }' | python -mijson.dump -m items -p domains.this.co.uk.item
#: value
--------
0: a
1: b
2: c
```

The limitations of the current prefix format is *not* that it cannot match keys with dots, but rather than it cannot distinguish between different paths that use the same prefix (e.g., nested "domains" + "this.co.uk" objects  and nested "domains" + "this" + "co" + "uk" objects match the same prefix). I'm well aware of this, but it's never been reported as a problem people experience in practice, and thus there's no urgency to improve the situation.

**Comment by mrsant** [comment]
Thanks! Looks like I made a stupid typo while testing the (correctly formatted) raw prefix ::rolls eyes:: feel free to delete!
