### ISSUE TITLE
Release wheels for 3.11

### ISSUE THREAD

**Issue by gaborbernat** [ICRAR/ijson#80]
👍

**Comment by rtobar** [comment]
Will do when I publish a new version of ijson, hopefully soon. Different binary wheels have been requested recently a few times, but our Travis-based pipeline needs to be ported to GitHub actions first to trigger all the builds and publishing.

**Comment by dchaplinsky** [comment]
Please do release! Want to make my package compatible with 3.11 to see if there is a performance gain after the upgrade

**Comment by rtobar** [comment]
@dchaplinsky the package is compatible already with 3.11, so you can go and install it without problems -- except that you'll need a compiler if you want to test the `yajl2_c` backend in particular. This issue is to release binary wheels; the source distribution for 3.1.4 should work without problems.

In any case I was just doing some successful tests with cibuildwheel on GH Actions yesterday, so I might be able to release one of these days.

**Comment by dchaplinsky** [comment]
Thanks, much appreciated

**Comment by rtobar** [comment]
A new 3.2.0 version of ijson has been tagged with source distribution and binary wheels published on PyPI (for version 3.2.0.post0, as there was a small problem when publishing 3.2.0).

**Comment by dchaplinsky** [comment]
Thanks! Now my package works under 3.11!
