### ISSUE TITLE
HighLevelAPI: Raise an error if the prefix does not exist

### ISSUE THREAD

**Issue by TekTimmy** [ICRAR/ijson#84]
**Is your feature request related to a problem? Please describe.**
When using `ijson.items` with an prefix that does not exist in the JSON it returns an empty iterator which is the same behavior as if the prefix leads to an empty array. I need to ensure the given prefix exists.
Example:
```python
json = io.BytesIO(b"""{}""")
ijson.items(json, 'path.item')
```

**Describe the solution you'd like**
If the prefix does not exist in the JSON an error should be raised.

**Describe alternatives you've considered**
None yet

**Comment by rtobar** [comment]
Thanks @TekTimmy for taking the time to record this suggestion.

I think there is a misunderstanding on how the prefix works (which is understandable, it's not easy subject): even in a document like `{"path": []}` the prefix `path.item` doesn't appear, because there are no items within the list. The empty list *itself* appears under the `path` prefix though. You can verify this by running:

```
$> echo '{"path": []}' | python -mijson.dump -m parse 
#: path, name, value
--------------------
0: , start_map, None
1: , map_key, path
2: path, start_array, None
3: path, end_array, None
4: , end_map, None
```

As you can see, `start_array` and `end_array` both happen in `path`, not in `path.item`, and thus `path.item` is never seen.

All this is to say that, from `ijson`'s perspective there's nothing different between your example of an empty document, and the example with an empty array, as in both cases the `path.item` prefix is never seen. This means there's no way to tell there is an actual error, at least using this method.

What you *could* do if you really want to check if the array is there or not is check if you see a `start_array` event in the `path` prefix. This requires you to use the lower-level `ijson.parse` function. More details can be found in the `README` of the project.

I hope this clarifies things.

**Comment by TekTimmy** [comment]
thank you for the nice explanation. I will implement a "has_path" method with the low level api then. Thank you.
