### ISSUE TITLE
Question: is it possible that returing bytes instead of str could speedup parsing? 

### ISSUE THREAD

**Issue by karlicoss** [ICRAR/ijson#90]
**Description**

I'm using `yajl2_c` backend.

I have a JSON file which vaguely looks like this:

```
[
{"key": "1", "value": some_huge_json_object}_1,
{"key": "2", "value": some_huge_json_object_2},
{"key": "3", "value": some_huge_json_object_3},
{"key": "4", "value": some_huge_json_object_4},
{"key": "5", "value": some_huge_json_object_5},
...
]
```

The actual file has lots more fields and more complex in general, but I think this communicates the essence of what I'm trying to achieve.
I want to process items depending on `key` field, certain keys (and corresponding objects) I just want to ignore completely.

From the docs I clearly need to use `ijson.parse` method for that, however it doesn't really give me speedup over basic `ijson.items`.
I think this is because the objects themselves don't have too many fields, so the overhead from creating `dict/list` objects is relatively small). 

However I have some quite long strings in these objects, and I *suspect* that the parser might spend significant time decoding these strings from bytes to unicode.
I don't have a good way to prove my suspicion because the parser is in a native library, so not really sure how to profile that (without building myself/running `perf` etc).
My hunch comes from seeing performance stats for builtin `json` module -- most time from parsing was spent decoding `bytes`.
It's possible that native `yajl` library is way more efficient at decoding unicode and returning `bytes` wouldn't give any significant speedup for me, but I couldn't find any past relevant discussions -- so please let me know if that's the case :) 

Obviously parser needs to read and tokenize the whole file even if I only want to process it only partially. However it doesn't really need to decode all bytes into unicode strings.

E.g. hypothetical parsing mode that might help me would work just as `ijson.parse`, but return `bytes` instead of `str` as `value`, leaving the decision to decode the string to the user.

Thanks!

**Why is this not clear from the documentation**

Docs mention that `ijson` returns unicode strings like builtin `json` which makes sense for 'basic' usage, but my usecase sort of falls under advance usecase, so perhaps it's possible :)

**Comment by rtobar** [comment]
@karlicoss thanks for a very well posed question. It opens a nice discussion, so I'm pretty happy that you asked this :). Hopefully my answer below makes sense.

The answer to the question in the title is: yes, returning bytes instead of strings does speed things up, as your correctly expected. I went ahead and measured this again (I've done in the past), exactly like you suggest, using `perf` to find out how much of our time is spent in decoding bytes into unicode strings. I used the `benchmark.py` tool found in `ijson` with ` -b big_longstr_object -B yajl2_c -s 4000000`, and a small internal change to run the same benchmark 20 times (so that the cost of building the JSON string to be parsed would become negligible). These are the results:

```
$> perf record --call-graph dwarf python benchmark.py -b big_longstr_object -B yajl2_c -s 4000000
#mbytes,method,test_case,backend,time,mb_per_sec
327.004, basic_parse, big_longstr_object, yajl2_c, 0.616, 530.838
327.004, basic_parse, big_longstr_object, yajl2_c, 0.621, 526.875
327.004, basic_parse, big_longstr_object, yajl2_c, 0.623, 525.046
327.004, basic_parse, big_longstr_object, yajl2_c, 0.625, 523.244
327.004, basic_parse, big_longstr_object, yajl2_c, 0.626, 522.055
327.004, basic_parse, big_longstr_object, yajl2_c, 0.626, 522.496
327.004, basic_parse, big_longstr_object, yajl2_c, 0.625, 522.808
327.004, basic_parse, big_longstr_object, yajl2_c, 0.627, 521.410
327.004, basic_parse, big_longstr_object, yajl2_c, 0.626, 522.086
327.004, basic_parse, big_longstr_object, yajl2_c, 0.626, 522.158
327.004, basic_parse, big_longstr_object, yajl2_c, 0.623, 525.274
327.004, basic_parse, big_longstr_object, yajl2_c, 0.615, 532.030
327.004, basic_parse, big_longstr_object, yajl2_c, 0.616, 530.781
327.004, basic_parse, big_longstr_object, yajl2_c, 0.621, 526.353
327.004, basic_parse, big_longstr_object, yajl2_c, 0.636, 513.840
327.004, basic_parse, big_longstr_object, yajl2_c, 0.597, 547.798
327.004, basic_parse, big_longstr_object, yajl2_c, 0.602, 543.050
327.004, basic_parse, big_longstr_object, yajl2_c, 0.607, 538.797
327.004, basic_parse, big_longstr_object, yajl2_c, 0.605, 540.515
327.004, basic_parse, big_longstr_object, yajl2_c, 0.601, 544.254
```

![image](https://user-images.githubusercontent.com/620848/227407590-dd96ee2a-ae9f-4ec3-9394-8498d5fd2129.png)

Like I mentioned, I knew this was a cost we run into. However, I think it's important to keep things in perspective: 13% of the time in this string-heavy JSON document isn't too big a cost for returning unicode strings instead of bytes, which most users won't know how to deal with. Also note the speed at which the benchmark ran: 500+ MB/s is probably only possible because we have all the contents of the JSON document in memory. If we were reading from a file, or receiving data from the network, the bottleneck will most likely be in doing that I/O rather than being in the bytes->unicode decoding bit.

Yes, a new option to toggle the behaviour could be added, but it doesn't come for free, as it would add more complexity to the codebase. I'm not completely shut to the idea for sure, but I'm not too eager to jump into it either, even less considering my point above about the overall performance of the system, and also based on the fact that this topic has only been brought up by yourself, and after many millions of downloads of the library -- so users in general seem to be fairly content with the current performance.

**Comment by karlicoss** [comment]
> thanks for a very well posed question

least I could do for an excellent project like this :) 

Thanks for the benchmarks!
Yeah, totally agree 13% is not worth the trouble even for me as a library user, this would increase the complexity on my side as well. Like I suspected, seems that decoding UTF in C is much faster than in Python -- in the latter case decoding did take considerable proportion of time for me.

**Comment by rtobar** [comment]
Yeap, I didn't mention it but indeed having ijson return strings *or* bytes would also be added complexity for users.

I'll be closing this issue now as the question has been answered. It can be useful to point people to some performance numbers in the future if required.
