### ISSUE TITLE
How can I most-efficiently check for a key in the top-level of a json object?

### ISSUE THREAD

**Issue by vuciv** [ICRAR/ijson#94]
**Description**

I am wondering how to efficiently check for a key in the top-level of a JSON object using the ijson library.

**Detailed description**

I am working on a Python project that involves processing large JSON documents. I need to check whether a specific key exists in the top-level of the JSON object. I am considering using the ijson library for parsing the JSON documents due to its ability to handle large files efficiently. However, I am unsure about the most efficient way to check for a key in the top-level of the JSON object using this library.

Here is an example of the JSON document format:

```json
{
  "name": "John Doe",
  "age": 30,
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip": "12345"
  },
  "email": "johndoe@example.com"
}
```

And here is an example of the Python code I am using to parse the JSON document using the ijson library:

```python
def file_check(file_name):
    key_to_check = 'email'
    with gzip.open(file_name, 'rt', encoding='utf-8') as file:
        parser = ijson.parse(file)

        # Iterate through JSON objects
        for prefix, event, value in parser:
            # Check if the current key matches the desired key and is a top-level key
            if event == 'map_key' and value == key_to_check and not prefix:
                return True
    return False
```

I would like to know the most efficient way to check for a key in the top-level of the JSON object using the ijson library. This is just an example, but using the parse function, the python will iterate over millions of nested objects in my case before it can actually figure out if the key is even present.

**Why is this not clear from the documentation**
I have read the ijson documentation, but it does not provide specific guidance on how to efficiently check for a key in the top-level of a JSON object. The documentation primarily focuses on parsing JSON objects using various functions provided by the library. Additionally, there is no example code that demonstrates how to efficiently check for a key in the top-level of a JSON object using the ijson library. I may be misunderstanding, however.

**Comment by rtobar** [comment]
@vuciv thanks for the very clearly posed question. I'm currently on leave, so until I'm back I leave you a very quick, broad answer: it depends. What you pose seems correct, but also consider using `kvitems`, it might or not be faster.

**Comment by rtobar** [comment]
@vuciv a more detailed response now. Like I said, it depends, and you'll also need to do your own benchmarking to see what's the fastest in your environment and given your input documents.

What you showed should work fine. It involves a bit of python code in the hot loop though, so my first suggestion would be to try `kvitems` and compare. `kvitems` does create more objects as the parsing process progresses, and might consume a bit more of memory because of that (depending on your input data), but if you're using the `yajl2_c` backend (most probably you are, it's the default one in most installations) then everything will happen in C instead of in python.

So here are some ideas for the main `for` loop you currently have within the `with gzip.open()` block:

* Use `kvitems`:
```python
for key, value in ijson.kvitems(file, ''):
    if key == key_to_check:
        return True
return False
```

Remove the explicit `for` and `if` and hopefully make the iteration itself faster too:

```python
return any(key == key_to_check for key, _value in ijson.kvitems(file, ''))
```
If it turns out that using `parse` is faster than `kvitems` then you can still try to use `any`:

```python
expected_result = ('', 'map_key', key_to_check):
return any(expected_result == parse_result for parse_result in ijson.parse(file))
```

Maybe other people can find other ways to do the same, but this should get you most of the way there.

Also note that how long it takes obviously depends on how far into the document your key is. If it's at the beginning then you're lucky and you'll exit fast, but if it's towards the end there's no way to simply "skip" the document, and you'll have to parse it fully until you find your key.

**Comment by vuciv** [comment]
@rtobar Thank you for the detailed and quick response. This answered my question!
